kind: kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml
- https://github.com/jetstack/cert-manager/releases/download/v1.0.2/cert-manager.yaml
- cluster-issuer.yml
- external-dns.yml
- ingress.yml
