apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- ingress.yml
- namespace.yml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
