apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.3/manifests/cluster-install/kustomization.yaml

resources:
- ingress.yml
- namespace.yml
