on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: true
        default: dev
      ref:
        description: 'Deployable ref, commit or branch'
        required: true
      name:
        description: 'Name of deployment/docker tag.'
        required: false
jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
    -
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - run: echo Deploying ${{ github.event.inputs.ref }} to ${{ github.event.inputs.name }}@${{ github.event.inputs.env }}

